name: 3D Calendar Only

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-3d-contrib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "update 3d calendar" || echo "Nada novo"
          git push
